In [1]:
import spacy

In [2]:
nlp = spacy.load('en_core_web_sm')

In [3]:
import numpy as np

In [4]:
def computeMED(str1, str2, insCost=1, delCost=1, subCost=2):
    M = len(str1)+1
    N = len(str2)+1
    D = np.zeros((M,N))

    for i in range(M):
        D[i,0] = i*delCost
    for j in range(N):
        D[0,j] = j*insCost

    for i in range(1, M):
        for j in range(1, N):
            diag = subCost if str1[i-1]!=str2[j-1] else 0
            D[i,j] = min(D[i-1,j]+delCost, D[i,j-1]+insCost, D[i-1,j-1]+diag)
    print(D)
    print('MED = ', D[M-1,N-1])
    

In [5]:
computeMED('INTENTION', 'EXECUTION')

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]
MED =  8.0
