In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.random.rand(3,4)

In [3]:
A

array([[0.18332301, 0.46540736, 0.89748204, 0.94901883],
       [0.643083  , 0.23485914, 0.0204858 , 0.76593001],
       [0.54155563, 0.00154791, 0.26097949, 0.0645092 ]])

In [4]:
ATA = A.T.dot(A)
AAt = A.dot(A.T)

In [5]:
ATA

array([[0.74044556, 0.23719208, 0.31903808, 0.70146887],
       [0.23719208, 0.27176522, 0.42291   , 0.62166587],
       [0.31903808, 0.42291   , 0.87400398, 0.88425362],
       [0.70146887, 0.62166587, 0.88425362, 1.49144696]])

In [6]:
AAt

array([[1.95632209, 0.97246472, 0.39544486],
       [0.97246472, 1.05578301, 0.40338466],
       [0.39544486, 0.40338466, 0.36555662]])

In [7]:
d1,V = LA.eig(ATA)

In [8]:
d1

array([2.70746231e+00, 4.93429462e-01, 1.76769945e-01, 9.29293597e-17])

In [9]:
V

array([[-0.37514385, -0.812732  , -0.43526408, -0.09632739],
       [-0.30656897,  0.14835409,  0.1909561 , -0.9206206 ],
       [-0.48660495,  0.56307659, -0.6577411 ,  0.11634871],
       [-0.7269788 , -0.02006276,  0.58434373,  0.36005793]])

In [10]:
ATA.dot(V[:,1])

array([-0.40102591,  0.07320228,  0.27783858, -0.00989956])

In [11]:
d1[1]*V[:,1]

array([-0.40102591,  0.07320228,  0.27783858, -0.00989956])