In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.random.rand(3,4)

In [3]:
A

array([[0.01066073, 0.29016479, 0.46729183, 0.35822118],
       [0.50721996, 0.44444832, 0.24693091, 0.51093238],
       [0.19591039, 0.82386755, 0.14793672, 0.75921747]])

In [4]:
ATA = A.T.dot(A)
AAT = A.dot(A.T)

In [5]:
ATA

array([[0.29576662, 0.38993064, 0.1592123 , 0.41171259],
       [0.38993064, 0.96048766, 0.36721993, 0.95652086],
       [0.1592123 , 0.36721993, 0.3012218 , 0.40587497],
       [0.41171259, 0.95652086, 0.40587497, 0.96578549]])

In [6]:
AAT

array([[0.43099332, 0.43278618, 0.58224331],
       [0.43278618, 0.77683317, 0.88997515],
       [0.58224331, 0.88997515, 1.31543507]])

In [7]:
d1,V = LA.eig(ATA)

In [8]:
d1

array([ 2.26321436e+00, -7.87046641e-17,  1.16298141e-01,  1.43749069e-01])

In [9]:
V

array([[ 0.28667903,  0.11395446, -0.86002209, -0.40643758],
       [ 0.64357472,  0.62942386,  0.38973863, -0.19427041],
       [ 0.27872977,  0.17951312, -0.30519134,  0.89271664],
       [ 0.65263805, -0.74740553,  0.12379034, -0.01115787]])

In [10]:
ATA.dot(V[:,0])

array([0.6488161 , 1.45654755, 0.63082522, 1.47705981])

In [11]:
d1[0]*V[:,0]

array([0.6488161 , 1.45654755, 0.63082522, 1.47705981])

In [12]:
idx = np.argsort(d1)[::-1]
d1 = d1[idx]
V = V[:,idx]

In [13]:
d1

array([ 2.26321436e+00,  1.43749069e-01,  1.16298141e-01, -7.87046641e-17])

In [14]:
V

array([[ 0.28667903, -0.40643758, -0.86002209,  0.11395446],
       [ 0.64357472, -0.19427041,  0.38973863,  0.62942386],
       [ 0.27872977,  0.89271664, -0.30519134,  0.17951312],
       [ 0.65263805, -0.01115787,  0.12379034, -0.74740553]])

In [15]:
d2,U = LA.eig(AAT)
idx = np.argsort(d2)[::-1]
d2 = d2[idx]
U = U[:,idx]

In [16]:
d1

array([ 2.26321436e+00,  1.43749069e-01,  1.16298141e-01, -7.87046641e-17])

In [17]:
d2

array([2.26321436, 0.14374907, 0.11629814])

In [18]:
U

array([[ 0.36814442,  0.92962095,  0.01657025],
       [ 0.55419228, -0.20508909, -0.80672758],
       [ 0.74655248, -0.30617536,  0.59069116]])

In [19]:
V

array([[ 0.28667903, -0.40643758, -0.86002209,  0.11395446],
       [ 0.64357472, -0.19427041,  0.38973863,  0.62942386],
       [ 0.27872977,  0.89271664, -0.30519134,  0.17951312],
       [ 0.65263805, -0.01115787,  0.12379034, -0.74740553]])

## Now do this(SVD) using builtin np function

In [20]:
U2,S2,V2 = LA.svd(A)

In [21]:
U

array([[ 0.36814442,  0.92962095,  0.01657025],
       [ 0.55419228, -0.20508909, -0.80672758],
       [ 0.74655248, -0.30617536,  0.59069116]])

In [22]:
U2

array([[ 0.36814442,  0.92962095,  0.01657025],
       [ 0.55419228, -0.20508909, -0.80672758],
       [ 0.74655248, -0.30617536,  0.59069116]])

In [23]:
d2

array([2.26321436, 0.14374907, 0.11629814])

In [24]:
S2 #here S2 is small than d2 because it is showing after square rooting the d2

array([1.50439834, 0.37914254, 0.34102513])

In [25]:
d2**.5

array([1.50439834, 0.37914254, 0.34102513])

In [26]:
V

array([[ 0.28667903, -0.40643758, -0.86002209,  0.11395446],
       [ 0.64357472, -0.19427041,  0.38973863,  0.62942386],
       [ 0.27872977,  0.89271664, -0.30519134,  0.17951312],
       [ 0.65263805, -0.01115787,  0.12379034, -0.74740553]])

In [27]:
V2 #is is transpose of V

array([[ 0.28667903,  0.64357472,  0.27872977,  0.65263805],
       [-0.40643758, -0.19427041,  0.89271664, -0.01115787],
       [-0.86002209,  0.38973863, -0.30519134,  0.12379034],
       [-0.11395446, -0.62942386, -0.17951312,  0.74740553]])

In [28]:
V2.T

array([[ 0.28667903, -0.40643758, -0.86002209, -0.11395446],
       [ 0.64357472, -0.19427041,  0.38973863, -0.62942386],
       [ 0.27872977,  0.89271664, -0.30519134, -0.17951312],
       [ 0.65263805, -0.01115787,  0.12379034,  0.74740553]])

## Testing the builtin one

In [29]:
D2 = np.hstack((np.diag(S2),np.zeros((3,1))))

In [30]:
S2

array([1.50439834, 0.37914254, 0.34102513])

In [31]:
D2

array([[1.50439834, 0.        , 0.        , 0.        ],
       [0.        , 0.37914254, 0.        , 0.        ],
       [0.        , 0.        , 0.34102513, 0.        ]])

In [32]:
test = U2.dot(D2).dot(V2)
test

array([[0.01066073, 0.29016479, 0.46729183, 0.35822118],
       [0.50721996, 0.44444832, 0.24693091, 0.51093238],
       [0.19591039, 0.82386755, 0.14793672, 0.75921747]])

In [33]:
A

array([[0.01066073, 0.29016479, 0.46729183, 0.35822118],
       [0.50721996, 0.44444832, 0.24693091, 0.51093238],
       [0.19591039, 0.82386755, 0.14793672, 0.75921747]])

## testing the manual one

In [34]:
d2_Matrix = np.hstack((np.diag(d2**.5),np.zeros((3,1))))
d2_Matrix

array([[1.50439834, 0.        , 0.        , 0.        ],
       [0.        , 0.37914254, 0.        , 0.        ],
       [0.        , 0.        , 0.34102513, 0.        ]])

In [35]:
test2 = U.dot(d2_Matrix).dot(V.T)

In [36]:
test2

array([[0.01066073, 0.29016479, 0.46729183, 0.35822118],
       [0.50721996, 0.44444832, 0.24693091, 0.51093238],
       [0.19591039, 0.82386755, 0.14793672, 0.75921747]])

In [37]:
A

array([[0.01066073, 0.29016479, 0.46729183, 0.35822118],
       [0.50721996, 0.44444832, 0.24693091, 0.51093238],
       [0.19591039, 0.82386755, 0.14793672, 0.75921747]])